/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Componentes;

import com.mycompany.maestria.Controlador.ControllerEstudiante;
import com.mycompany.maestria.Controlador.ControllerTesis;
import com.mycompany.maestria.Modelo.Estudiante;
import com.mycompany.maestria.Modelo.Tesis;
import com.mycompany.maestria.Modelo.Usuario;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omarsilverio
 */
public class AlertaConfirmacion extends javax.swing.JDialog {
    private boolean confirmacion = false;
    private ControllerEstudiante ce;
    private ControllerTesis ct;
    private JTable tabla;
    private Estudiante estudiante;  
    private Tesis tesis;
    /**
     * Creates new form AlertaConfirmacion
     */
    public AlertaConfirmacion(JDialog parent) {
        super(parent);
        initComponents();
        this.setTitle("Confirmación");
    }
    
    public AlertaConfirmacion(JDialog parent, Estudiante estudiante, JTable tabla, ControllerEstudiante ce) {       
        super(parent);
        this.tabla = tabla;
        this.estudiante = estudiante;
        this.ce = ce;
        initComponents();
        this.setTitle("Confirmación");
    }
    
    public AlertaConfirmacion(JDialog parent, Tesis tesis, JTable tabla, ControllerTesis ct) {       
        super(parent);
        this.tabla = tabla;
        this.tesis = tesis;
        this.ct = ct;
        initComponents();
        this.setTitle("Confirmación");
    }
    
    public boolean getConfirmacion(){
        return confirmacion;
    }
    
    public void setConfirmacion(){
        String passwordTemp = new String(entradaContrasenia.getPassword());
        Usuario usuTemp = new Usuario();
        if(passwordTemp.equals(usuTemp.getPassword())){
            if(estudiante != null) eliminarEstudiante();
            else if(tesis != null) eliminarTesis();
            confirmacion = true;
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
            entradaContrasenia.selectAll();
        }        
    }
    
    public void eliminarEstudiante(){
        if(ce.removeEstudiante(estudiante, this)){
            int rowSelected = tabla.getSelectedRow();            
            ((DefaultTableModel)(tabla.getModel())).removeRow(rowSelected);
        }
    }
    
    public void eliminarTesis(){
        if(ct.removeTesis(tesis, this)){
            int rowSelected = tabla.getSelectedRow();            
            ((DefaultTableModel)(tabla.getModel())).removeRow(rowSelected);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        letrero = new javax.swing.JLabel();
        letreroContrasenia = new javax.swing.JLabel();
        entradaContrasenia = new javax.swing.JPasswordField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        letrero.setText("Esta acción requiere confirmación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        add(letrero, gridBagConstraints);

        letreroContrasenia.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 15, 0, 0);
        add(letreroContrasenia, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 193;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 6);
        add(entradaContrasenia, gridBagConstraints);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 6, 6, 0);
        add(btnCancelar, gridBagConstraints);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 104, 6, 6);
        add(btnAceptar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        setConfirmacion();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPasswordField entradaContrasenia;
    private javax.swing.JLabel letrero;
    private javax.swing.JLabel letreroContrasenia;
    // End of variables declaration//GEN-END:variables
}
