/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Componentes;

import com.mycompany.maestria.Controlador.ControllerPrestamo;
import com.mycompany.maestria.Controlador.ControllerTesis;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Modelo.Tesis;
import com.mycompany.maestria.Vista.Colores.Colores;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author omarsilverio
 */
public class AlumnosAdeudos extends javax.swing.JDialog {
    Tesis tesis;
    /**
     * Creates new form AlumnosAdeudos
     */
    public AlumnosAdeudos(Tesis tesis, JDialog parent) {
        super(parent);
        this.tesis = tesis;
        initComponents();
        mostrarAdeudos();
        RenderTabla.cambiarEstiloEncabezados(tablaAdeudos);
    }
    
    private void mostrarAdeudos(){
        DefaultTableModel temp = ControllerPrestamo.estudiantesAdeudos(tesis);
        if(temp != null && temp.getRowCount() > 0){
            tablaAdeudos.setModel(temp);
             RenderTabla.centrarDatos(tablaAdeudos);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        letreroConsulta = new javax.swing.JLabel();
        barraHeramientas = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnView = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdeudos = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.BorderLayout());

        letreroConsulta.setBackground(Colores.colorPrimary);
        letreroConsulta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        letreroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setText("Prestamos Tesis");
        letreroConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setOpaque(true);
        jPanel1.add(letreroConsulta, java.awt.BorderLayout.NORTH);

        barraHeramientas.setMinimumSize(new java.awt.Dimension(1103, 38));
        barraHeramientas.setPreferredSize(new java.awt.Dimension(1103, 38));
        barraHeramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setToolTipText("Menú");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnHome);
        barraHerramientas.add(jSeparator3);

        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        btnView.setToolTipText("Información de la Tesis");
        btnView.setFocusable(false);
        btnView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnView);
        barraHerramientas.add(jSeparator1);

        barraHeramientas.add(barraHerramientas);

        jPanel1.add(barraHeramientas, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        tablaAdeudos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero Prestamo", "Numero Control", "Nombre", "Cant. Unidades", "Fecha Prestamo"
            }
        ));
        jScrollPane1.setViewportView(tablaAdeudos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
       ControllerTesis.dialogViewTesis(tesis, this);

    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barraHeramientas;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel letreroConsulta;
    private javax.swing.JTable tablaAdeudos;
    // End of variables declaration//GEN-END:variables
}
