/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Componentes;

import javax.swing.JFrame;




/**
 *
 * @author omarsilverio
 */
import com.mycompany.maestria.Vista.Colores.Colores;
import java.awt.Color;
public class Head extends javax.swing.JPanel {
    private JFrame parent;
    /**
     * Creates new form Head
     */
    public Head(JFrame parent) {
        this.parent = parent;       
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        imagenDivision = new javax.swing.JLabel();
        panelInstitucion = new javax.swing.JPanel();
        letreroNombreEscuela = new javax.swing.JLabel();
        letreroDepartamento = new javax.swing.JLabel();
        letreroCoordinacion = new javax.swing.JLabel();
        letreroTitulo = new javax.swing.JLabel();
        imagenIto = new javax.swing.JLabel();

        setBackground(Colores.colorPrimary);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        imagenDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consejoAcademico.jpeg"))); // NOI18N
        add(imagenDivision);

        panelInstitucion.setBackground(Colores.colorPrimary);
        panelInstitucion.setLayout(new java.awt.GridBagLayout());

        letreroNombreEscuela.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        letreroNombreEscuela.setForeground(new java.awt.Color(255, 255, 255));
        letreroNombreEscuela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroNombreEscuela.setText("Instituto Tecnológico De Oaxaca");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelInstitucion.add(letreroNombreEscuela, gridBagConstraints);

        letreroDepartamento.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        letreroDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        letreroDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroDepartamento.setText("División De Estudios De Posgrado E Investigación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelInstitucion.add(letreroDepartamento, gridBagConstraints);

        letreroCoordinacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        letreroCoordinacion.setForeground(new java.awt.Color(255, 255, 255));
        letreroCoordinacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroCoordinacion.setText("Maestría En Ciencias En Desarrollo Regional Y Tecnológico");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelInstitucion.add(letreroCoordinacion, gridBagConstraints);

        letreroTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        letreroTitulo.setForeground(new java.awt.Color(255, 255, 255));
        letreroTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTitulo.setText("Control De Tesis Y Prestamos");
        letreroTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroTitulo.setPreferredSize(new java.awt.Dimension(274, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 339;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelInstitucion.add(letreroTitulo, gridBagConstraints);

        add(panelInstitucion);

        imagenIto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoito.png"))); // NOI18N
        add(imagenIto);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenDivision;
    private javax.swing.JLabel imagenIto;
    private javax.swing.JLabel letreroCoordinacion;
    private javax.swing.JLabel letreroDepartamento;
    private javax.swing.JLabel letreroNombreEscuela;
    private javax.swing.JLabel letreroTitulo;
    private javax.swing.JPanel panelInstitucion;
    // End of variables declaration//GEN-END:variables
}
