/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Formularios;

import com.mycompany.maestria.Controlador.ControllerDevolucion;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Modelo.Estudiante;
import com.mycompany.maestria.Vista.Colores.Colores;

import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author omarsilverio
 */
public class FormularioAdeudo extends javax.swing.JDialog {
    
    private final Estudiante estudianteTemp;      
    private ControllerDevolucion cd = new ControllerDevolucion();
 

    /**
     * Creates new form AdeudosTesis
     * @param componente
     * @param modal
     * @param estudianteTemp 
     */    
    public FormularioAdeudo(JDialog componente,boolean modal,Estudiante estudianteTemp) {
        super(componente,modal);
        this.estudianteTemp = estudianteTemp;
        initComponents();   
        mostrarAdeudos();
        btnRecuperar.setEnabled(false);
        asignarEntradas();
        bloquearEntradas();     
        RenderTabla.cambiarEstiloEncabezados(tablaAdeudos);
    }
    public void mostrarAdeudos(){
        DefaultTableModel modelTemp = cd.getAdeudosEstudiantes(estudianteTemp);
        if(modelTemp != null && modelTemp.getRowCount() > 0){
            scrollTabla.setVisible(true);
            letreroTabla.setVisible(false);
            tablaAdeudos.setModel(modelTemp);
        }else{
            scrollTabla.setVisible(false);
            letreroTabla.setVisible(true);
        }
        
    }
    /**
     * Bloque las entradas del formulario
     */
    private void bloquearEntradas(){
        inNumeroControl.setEditable(false);
        inNombre.setEditable(false);
        inPrimerApellido.setEditable(false);
        inSegundoApellido.setEditable(false);
    }
    /**
     * Rellena las estradas con los datos del estudiante
     */
    private void asignarEntradas(){
        inNumeroControl.setText(estudianteTemp.getNumero_control());
        inNombre.setText(estudianteTemp.getNombre());
        inPrimerApellido.setText(estudianteTemp.getApellido_paterno());
        inSegundoApellido.setText(estudianteTemp.getApellido_materno());        
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        letreroConsulta = new javax.swing.JLabel();
        areaFormulario = new javax.swing.JPanel();
        areaEstudiante = new javax.swing.JPanel();
        inNombre = new javax.swing.JTextField();
        inSegundoApellido = new javax.swing.JTextField();
        inPrimerApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inNumeroControl = new javax.swing.JTextField();
        areaAdeudos = new javax.swing.JPanel();
        areaTabla = new javax.swing.JPanel();
        letreroListaTesis = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        letreroTabla = new javax.swing.JLabel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaAdeudos = new javax.swing.JTable();
        areaBarra = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnRecuperar = new javax.swing.JButton();
        areaBotones = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();

        letreroConsulta.setBackground(Colores.colorPrimary);
        letreroConsulta.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        letreroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setText("Información Estudiante");
        letreroConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setOpaque(true);
        getContentPane().add(letreroConsulta, java.awt.BorderLayout.NORTH);

        areaFormulario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        areaFormulario.setLayout(new javax.swing.BoxLayout(areaFormulario, javax.swing.BoxLayout.Y_AXIS));

        areaEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMACIÓN DEL ESTUDIANTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        areaEstudiante.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 456;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        areaEstudiante.add(inNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 455;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 22, 0);
        areaEstudiante.add(inSegundoApellido, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 455;
        gridBagConstraints.ipady = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        areaEstudiante.add(inPrimerApellido, gridBagConstraints);

        jLabel7.setText("* Nombre(s):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 142, 0, 0);
        areaEstudiante.add(jLabel7, gridBagConstraints);

        jLabel8.setText("* Primer Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 111, 0, 0);
        areaEstudiante.add(jLabel8, gridBagConstraints);

        jLabel10.setText("* Segundo apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 99, 0, 0);
        areaEstudiante.add(jLabel10, gridBagConstraints);

        jLabel1.setText(" * Numero de control:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 85, 0, 0);
        areaEstudiante.add(jLabel1, gridBagConstraints);

        inNumeroControl.setMinimumSize(new java.awt.Dimension(11, 32));
        inNumeroControl.setPreferredSize(new java.awt.Dimension(81, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 0, 0);
        areaEstudiante.add(inNumeroControl, gridBagConstraints);

        areaFormulario.add(areaEstudiante);

        areaAdeudos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE ADEUDOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        areaAdeudos.setLayout(new java.awt.BorderLayout());

        areaTabla.setLayout(new java.awt.BorderLayout());

        letreroListaTesis.setText("Seleccione una tesis y presione recuperar");
        areaTabla.add(letreroListaTesis, java.awt.BorderLayout.NORTH);

        panelTabla.setLayout(new java.awt.CardLayout());

        letreroTabla.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTabla.setText("¡El estudiante no tiene adeudos!");
        panelTabla.add(letreroTabla, "letrero");

        tablaAdeudos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdTesis", "Autor", "Titulo"
            }
        ));
        tablaAdeudos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaAdeudosMousePressed(evt);
            }
        });
        scrollTabla.setViewportView(tablaAdeudos);

        panelTabla.add(scrollTabla, "card2");

        areaTabla.add(panelTabla, java.awt.BorderLayout.CENTER);

        areaAdeudos.add(areaTabla, java.awt.BorderLayout.CENTER);

        areaBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaBarra.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnRecuperar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book.png"))); // NOI18N
        btnRecuperar.setToolTipText("Recuperar");
        btnRecuperar.setFocusable(false);
        btnRecuperar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecuperar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRecuperar);

        areaBarra.add(jToolBar1);

        areaAdeudos.add(areaBarra, java.awt.BorderLayout.NORTH);

        areaFormulario.add(areaAdeudos);

        getContentPane().add(areaFormulario, java.awt.BorderLayout.CENTER);

        areaBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        areaBotones.setPreferredSize(new java.awt.Dimension(864, 45));
        areaBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 5));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        areaBotones.add(btnCancelar);

        getContentPane().add(areaBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        // TODO add your handling code here:       
       cd.dialogAlmacenamientoDevolcion(this, tablaAdeudos, estudianteTemp);    
       mostrarAdeudos();
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void tablaAdeudosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAdeudosMousePressed
        // TODO add your handling code here:
        btnRecuperar.setEnabled(true);
    }//GEN-LAST:event_tablaAdeudosMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaAdeudos;
    private javax.swing.JPanel areaBarra;
    private javax.swing.JPanel areaBotones;
    private javax.swing.JPanel areaEstudiante;
    private javax.swing.JPanel areaFormulario;
    private javax.swing.JPanel areaTabla;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JTextField inNombre;
    private javax.swing.JTextField inNumeroControl;
    private javax.swing.JTextField inPrimerApellido;
    private javax.swing.JTextField inSegundoApellido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel letreroConsulta;
    private javax.swing.JLabel letreroListaTesis;
    private javax.swing.JLabel letreroTabla;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaAdeudos;
    // End of variables declaration//GEN-END:variables
}
