/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.maestria.Vista;


import com.mycompany.maestria.Modelo.Usuario;
import com.mycompany.maestria.Vista.Componentes.Alertas;
import com.mycompany.maestria.Vista.Componentes.Footer;
import com.mycompany.maestria.Vista.MenuPrincipal;

import java.awt.Dimension;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author feli
 */
public class Login extends javax.swing.JFrame {
    private static final Footer footer = new Footer();
    private Usuario usuario;    
    /**
     * Creates new form Login
     */
    public Login(Usuario usuario){
        this.usuario = usuario;        
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(new Dimension(500,500));
        this.add(footer, BorderLayout.SOUTH);
        this.setExtendedState(MAXIMIZED_BOTH);
        rellenarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formLogin = new javax.swing.JPanel();
        letreroUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        letreroContrasena = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        iconoLogin = new javax.swing.JLabel();
        checkRecordar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(239, 239, 239));

        formLogin.setBackground(new java.awt.Color(239, 239, 239));
        formLogin.setLayout(new java.awt.GridBagLayout());

        letreroUsuario.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 135, 0, 0);
        formLogin.add(letreroUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 155);
        formLogin.add(txtUsuario, gridBagConstraints);

        letreroContrasena.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 112, 0, 0);
        formLogin.add(letreroContrasena, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 209;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 0, 155);
        formLogin.add(txtPassword, gridBagConstraints);

        btnEntrar.setText("Ingresar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 66, 120, 0);
        formLogin.add(btnEntrar, gridBagConstraints);

        iconoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 42, 0, 0);
        formLogin.add(iconoLogin, gridBagConstraints);

        checkRecordar.setText("Recordar Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 18, 0, 155);
        formLogin.add(checkRecordar, gridBagConstraints);

        getContentPane().add(formLogin, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void rellenarCampos(){
        if(usuario.getRemember()){            
            txtUsuario.setText(usuario.getUsuario());
            txtPassword.setText(usuario.getPassword());
            checkRecordar.setSelected(true);
        }else{
            checkRecordar.setSelected(false);
        }
    }
    
    public boolean comprobarInicioSesion(){
        String usuarioTemp = txtUsuario.getText();
        String passwordTemp = new String(txtPassword.getPassword());    
        return usuario.getUsuario().equals(usuarioTemp) && usuario.getPassword().equals(passwordTemp);
    }
      
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        if(comprobarInicioSesion()){
            this.dispose();            
            usuario.setRemember(checkRecordar.isSelected());
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MenuPrincipal(usuario.getUsuario()).setVisible(true);
                }
            });  
        }else{
            Alertas.mensajeError(this, "Usuario o contraseña incorrecto");
        }    
    }//GEN-LAST:event_btnEntrarActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox checkRecordar;
    private javax.swing.JPanel formLogin;
    private javax.swing.JLabel iconoLogin;
    private javax.swing.JLabel letreroContrasena;
    private javax.swing.JLabel letreroUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
