/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.maestria.Vista;



import com.mycompany.maestria.Controlador.Controller;
import com.mycompany.maestria.Vista.Componentes.Footer;
import com.mycompany.maestria.Vista.Componentes.Head;
import com.mycompany.maestria.Vista.Modulos.ModuloConfiguraciones;
import com.mycompany.maestria.Vista.Modulos.ModuloHistorial;
import com.mycompany.maestria.Vista.Modulos.ModuloEstudiantes;
import com.mycompany.maestria.Vista.Modulos.ModuloAdeudos;
import com.mycompany.maestria.Vista.Modulos.ModuloTesis;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author omarsilverio
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private static final Footer footer = new Footer();
    private final Head head;   
    private final Controller ct = new Controller();
    private String usuario;
    /**
     * Creates new form MenuPrincipal
     * @param usuario
     */
    public MenuPrincipal(String usuario) {   
        this.usuario = usuario;
        initComponents();        
        head = new Head(this);
        this.add(head, BorderLayout.NORTH);
        this.add(footer, BorderLayout.SOUTH);
        this.setExtendedState(MAXIMIZED_BOTH);
        btnMostrar.setToolTipText("Muestra los registros de las tesis de maestria");        
        letreroPrestamos.setToolTipText("Realiza un prestamo de una tesis");
        letreroBienvenida.setText("¡Bienvenido " + usuario + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelContenido = new javax.swing.JPanel();
        panelOpc = new javax.swing.JPanel();
        letreroBienvenida = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        btnPrestamo = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        letreroMostrar = new javax.swing.JLabel();
        letreroPrestamos = new javax.swing.JLabel();
        letreroAdminUsuarios = new javax.swing.JLabel();
        letreroEstadisticas = new javax.swing.JLabel();
        btnConfiguraciones = new javax.swing.JButton();
        letreroConfiguraciones = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenido.setLayout(new java.awt.BorderLayout());

        panelOpc.setLayout(new java.awt.GridBagLayout());

        letreroBienvenida.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        letreroBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        letreroBienvenida.setText("¡Bienvenido admin!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 698;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(74, 24, 0, 68);
        panelOpc.add(letreroBienvenida, gridBagConstraints);

        btnMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mostrar.png"))); // NOI18N
        btnMostrar.setToolTipText("Agrega, elimina , edita  y agrega tesis");
        btnMostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 96, 0, 0);
        panelOpc.add(btnMostrar, gridBagConstraints);

        btnPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestar.png"))); // NOI18N
        btnPrestamo.setToolTipText("Realiza prestamos de tesis");
        btnPrestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 100, 0, 68);
        panelOpc.add(btnPrestamo, gridBagConstraints);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users.png"))); // NOI18N
        btnUsuarios.setToolTipText("Agrega, Edita y Elimina  Usuarios");
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 99;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 0, 0);
        panelOpc.add(btnUsuarios, gridBagConstraints);

        btnEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crecimiento.png"))); // NOI18N
        btnEstadisticas.setToolTipText("Revisa las Estadísticas de los Prestamos");
        btnEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 24, 0, 0);
        panelOpc.add(btnEstadisticas, gridBagConstraints);

        letreroMostrar.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        letreroMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroMostrar.setText("Tesis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 212;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 100, 0, 0);
        panelOpc.add(letreroMostrar, gridBagConstraints);

        letreroPrestamos.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        letreroPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroPrestamos.setText("Adeudos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 180;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 100, 0, 0);
        panelOpc.add(letreroPrestamos, gridBagConstraints);

        letreroAdminUsuarios.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        letreroAdminUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroAdminUsuarios.setText("Estudiantes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 24, 0, 0);
        panelOpc.add(letreroAdminUsuarios, gridBagConstraints);

        letreroEstadisticas.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        letreroEstadisticas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroEstadisticas.setText("Estadísticas");
        letreroEstadisticas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 170;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 24, 126, 0);
        panelOpc.add(letreroEstadisticas, gridBagConstraints);

        btnConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ajustes.png"))); // NOI18N
        btnConfiguraciones.setToolTipText("Revisa las Estadísticas de los Prestamos");
        btnConfiguraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 96, 0, 0);
        panelOpc.add(btnConfiguraciones, gridBagConstraints);

        letreroConfiguraciones.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        letreroConfiguraciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConfiguraciones.setText("Configuraciones");
        letreroConfiguraciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 142;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 96, 126, 0);
        panelOpc.add(letreroConfiguraciones, gridBagConstraints);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log-out.png"))); // NOI18N
        btnSalir.setToolTipText("Salir del programa");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 101;
        gridBagConstraints.ipady = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 100, 0, 68);
        panelOpc.add(btnSalir, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salir");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 218;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 126, 68);
        panelOpc.add(jLabel1, gridBagConstraints);

        panelContenido.add(panelOpc, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(ct.comprobarTablas(this)){
            ModuloTesis form = new ModuloTesis();
            form.pack();
            form.setModal(true);
            form.setLocationRelativeTo(null);
            form.setVisible(true);   
        }   
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoActionPerformed
        if(ct.comprobarTablas(this)){
            ModuloAdeudos form = new ModuloAdeudos();
            form.pack();
            form.setModal(true);
            form.setLocationRelativeTo(null);
            form.setVisible(true); 
        } 
    }//GEN-LAST:event_btnPrestamoActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        if(ct.comprobarTablas(this)){
            ModuloEstudiantes form = new ModuloEstudiantes();
            form.pack();
            form.setModal(true);
            form.setLocationRelativeTo(null);
            form.setVisible(true); 
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        if(ct.comprobarTablas(this)){
            ModuloHistorial form = new ModuloHistorial();
            form.pack();
            form.setModal(true);
            form.setLocationRelativeTo(null);
            form.setVisible(true); 
        }
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnConfiguracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionesActionPerformed

        ModuloConfiguraciones form = new ModuloConfiguraciones();
        form.pack();
        form.setModal(true);
        form.setLocationRelativeTo(null);
        form.setVisible(true); 
        this.validate();
        
    }//GEN-LAST:event_btnConfiguracionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this, "El programa se cerrará "
                + "\n ¿Desea continuar?","Cerrar Programa",JOptionPane.YES_OPTION);
        if(resp == 0)
            System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguraciones;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnPrestamo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel letreroAdminUsuarios;
    private javax.swing.JLabel letreroBienvenida;
    private javax.swing.JLabel letreroConfiguraciones;
    private javax.swing.JLabel letreroEstadisticas;
    private javax.swing.JLabel letreroMostrar;
    private javax.swing.JLabel letreroPrestamos;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelOpc;
    // End of variables declaration//GEN-END:variables
}
