/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Modulos;

import com.mycompany.maestria.Controlador.ControllerEstudiante;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Vista.Componentes.NavBar;
import com.mycompany.maestria.Vista.Colores.Colores;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author omarsilverio
 */
public class ModuloEstudiantes extends javax.swing.JDialog {     
    private final ControllerEstudiante ce = new ControllerEstudiante();    
    private String categoria = "Estudiante";
    
    /**
     * Creates new form ConsultarEstudiantes
     */
    public ModuloEstudiantes() {  
        this.setJMenuBar(new NavBar(this));
        initComponents();
        mostrarTodosEstudiantes();
        RenderTabla.cambiarEstiloEncabezados(tablaEstudiantes);
    }
    /**
     * Muestra todos los registros de la tabla Tesis
     */
    public void mostrarTodosEstudiantes(){        
        DefaultTableModel temp = ce.allEstudiantes(categoria);   
        actualizarTabla(temp, "¡Lista Vacía!");              
        botonesAcciones(false);        
    }  
    /**
     * Controla las busquedas según sea la selección de busqueda
    */
     private void buscar(){
        int select = cmbBuscarPor.getSelectedIndex();
        String busqueda = txtBusqueda.getText();
        if(busqueda.isEmpty()){
            mostrarTodosEstudiantes();
        }else{
            DefaultTableModel temp = ce.busquedas(busqueda, categoria, select);
            actualizarTabla(temp, "¡No se encontrarón coincidencias!");   
        }      
     }
     /**
     * Muestra el resultado en la tabla
     */
    private void actualizarTabla(DefaultTableModel temp, String mensaje){
        if(temp != null && temp.getRowCount() > 0){
                tablaEstudiantes.setModel(temp);  
                RenderTabla.centrarDatos(tablaEstudiantes);
                tablaScroll.setVisible(true);                
                letreroTabla.setVisible(false);                
                btnVerDetalles.setEnabled(false);                
                
            }else{            
                tablaScroll.setVisible(false);
                letreroTabla.setText(mensaje);
                letreroTabla.setVisible(true);
                btnVerDetalles.setEnabled(false);              
                
            }        
    }    
    
    /**
     * Habilita o deshabilita los botones de editar, eliminar y ver
     */
    private void botonesAcciones(boolean state){
        btnEditar.setEnabled(state);
        btnEliminar.setEnabled(state);
        btnVerDetalles.setEnabled(state); 
    }    
    
    
    
    public void mostrarResultados(DefaultTableModel temp, String mensaje){
        if(temp != null  && temp.getRowCount() > 0){
                tablaEstudiantes.setModel(temp);                
                tablaScroll.setVisible(true);                
                letreroTabla.setVisible(false);
                btnReporte.setEnabled(true);
            }else{
                tablaScroll.setVisible(false);
                letreroTabla.setText(mensaje);
                letreroTabla.setVisible(true);
                btnReporte.setEnabled(false);
            }        
    } 
    
   
    
    public String  tablaSeleccionada(int selec){
        switch(selec){
            case 0 ->{
                panelTablaEstudiantes.add(tablaScroll);
                panelTablaEstudiantes.add(letreroTabla);
                return "Estudiante";
            }
            case 1 ->{
                panelTablaTitulados.add(tablaScroll);
                panelTablaTitulados.add(letreroTabla);
                return "Titulado";
            }
            case 2 ->{
                panelTablaInactivos.add(tablaScroll);
                panelTablaInactivos.add(letreroTabla);
                return "Inactivo";
            }
            default -> {
                panelTablaEstudiantes.add(tablaScroll);
                panelTablaEstudiantes.add(letreroTabla);
                return "Estudiante";
            }            
        }
        
    }    
    
    
   
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarCarpeta = new javax.swing.JFileChooser();
        panelTitulo = new javax.swing.JPanel();
        letreroConsulta = new javax.swing.JLabel();
        panelBarHerramientas = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVerDetalles = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAgregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnReporte = new javax.swing.JButton();
        panelBusqueda = new javax.swing.JPanel();
        letreroBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        panelTablas = new javax.swing.JTabbedPane();
        panelTablaEstudiantes = new javax.swing.JPanel();
        tablaScroll = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        letreroTabla = new javax.swing.JLabel();
        panelTablaTitulados = new javax.swing.JPanel();
        panelTablaInactivos = new javax.swing.JPanel();

        seleccionarCarpeta.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        seleccionarCarpeta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelTitulo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        panelTitulo.setMinimumSize(new java.awt.Dimension(188, 30));
        panelTitulo.setPreferredSize(new java.awt.Dimension(1103, 30));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        letreroConsulta.setBackground(Colores.colorPrimary);
        letreroConsulta.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setText("Lista de Estudiantes");
        letreroConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setMaximumSize(new java.awt.Dimension(18888, 22));
        letreroConsulta.setOpaque(true);
        panelTitulo.add(letreroConsulta, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTitulo);

        panelBarHerramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarHerramientas.setMaximumSize(new java.awt.Dimension(11033, 46));
        panelBarHerramientas.setMinimumSize(new java.awt.Dimension(1103, 46));
        panelBarHerramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setToolTipText("Menú");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnHome);
        barraHerramientas.add(jSeparator3);

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        btnVerDetalles.setToolTipText("Muestra los detalles de la tesis seleccionada");
        btnVerDetalles.setEnabled(false);
        btnVerDetalles.setFocusable(false);
        btnVerDetalles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerDetalles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnVerDetalles);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil.png"))); // NOI18N
        btnEditar.setToolTipText("Modifica el estudiante seleccionado");
        btnEditar.setEnabled(false);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnEditar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Elimina el estudiante seleccionado");
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnEliminar);
        barraHerramientas.add(jSeparator1);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAgregar.setToolTipText("Agrega un nuevo estudiante");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnAgregar);
        barraHerramientas.add(jSeparator2);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnReporte.setToolTipText("Genera un reporte de todos los estudiantes");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnReporte);

        panelBarHerramientas.add(barraHerramientas);

        getContentPane().add(panelBarHerramientas);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusqueda.setMaximumSize(new java.awt.Dimension(11038, 45));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(974, 45));
        panelBusqueda.setPreferredSize(new java.awt.Dimension(974, 45));
        panelBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        letreroBuscarPor.setText("Buscar por:");
        panelBusqueda.add(letreroBuscarPor);

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Control", "Nombre" }));
        cmbBuscarPor.setAutoscrolls(true);
        panelBusqueda.add(cmbBuscarPor);

        txtBusqueda.setMaximumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(500, 26));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        panelBusqueda.add(txtBusqueda);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnMostrarTodo);

        getContentPane().add(panelBusqueda);

        panelTablas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelTablasStateChanged(evt);
            }
        });

        panelTablaEstudiantes.setLayout(new java.awt.CardLayout());

        tablaEstudiantes.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Control", "Nombre", "Primer Apellido", "Segundo Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEstudiantes.setToolTipText("Tabla estudiantes");
        tablaEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaEstudiantesMousePressed(evt);
            }
        });
        tablaScroll.setViewportView(tablaEstudiantes);
        if (tablaEstudiantes.getColumnModel().getColumnCount() > 0) {
            tablaEstudiantes.getColumnModel().getColumn(0).setPreferredWidth(100);
            tablaEstudiantes.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        panelTablaEstudiantes.add(tablaScroll, "tabla");

        letreroTabla.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTabla.setText("¡Lista Vacía!");
        panelTablaEstudiantes.add(letreroTabla, "letrero");

        panelTablas.addTab("Activos", panelTablaEstudiantes);

        panelTablaTitulados.setLayout(new java.awt.CardLayout());
        panelTablas.addTab("Titulados", panelTablaTitulados);

        panelTablaInactivos.setLayout(new java.awt.CardLayout());
        panelTablas.addTab("Atrasados", panelTablaInactivos);

        getContentPane().add(panelTablas);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        mostrarTodosEstudiantes();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ce.dialogoEditEstudiante(this, tablaEstudiantes);       
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ce.dialogoAddEstudiante(this,tablaEstudiantes);
         
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        ce.generarReporte(seleccionarCarpeta, this, categoria);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void tablaEstudiantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEstudiantesMousePressed
            if(evt.getButton() == 1 && evt.getClickCount() == 1){                
                botonesAcciones(true);
            }else if (evt.getButton() == 1 && evt.getClickCount() > 1) {                
               ControllerEstudiante.dialogoViewEstudiante(this, tablaEstudiantes);
            }
    }//GEN-LAST:event_tablaEstudiantesMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:        
        ce.eliminarEstudiante(this, tablaEstudiantes);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
         ControllerEstudiante.dialogoViewEstudiante(this, tablaEstudiantes);        
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void panelTablasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelTablasStateChanged
        // TODO add your handling code here:
        int select = panelTablas.getSelectedIndex();
        if(select > -1) categoria = tablaSeleccionada(select);
        mostrarTodosEstudiantes();
    }//GEN-LAST:event_panelTablasStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel letreroBuscarPor;
    private javax.swing.JLabel letreroConsulta;
    private javax.swing.JLabel letreroTabla;
    private javax.swing.JPanel panelBarHerramientas;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelTablaEstudiantes;
    private javax.swing.JPanel panelTablaInactivos;
    private javax.swing.JPanel panelTablaTitulados;
    private javax.swing.JTabbedPane panelTablas;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JFileChooser seleccionarCarpeta;
    private javax.swing.JTable tablaEstudiantes;
    private javax.swing.JScrollPane tablaScroll;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
