/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Modulos;

import com.mycompany.maestria.Controlador.ControllerPrestamo;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Modelo.Estudiante;
import com.mycompany.maestria.Vista.Componentes.NavBar;
import com.mycompany.maestria.Vista.Colores.Colores;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author omarsilverio
 */
public class ModuloAdeudos extends javax.swing.JDialog {
    
    
    private final ControllerPrestamo cp = new ControllerPrestamo();     
  
    /**
     * Creates new form AdeudosTesis
     */
    public ModuloAdeudos() {   
        this.setJMenuBar(new NavBar(this));
        initComponents();
        this.setTitle("Adeudos");       
        mostrarTodosAdeudos();
        RenderTabla.cambiarEstiloEncabezados(tablaAlumnos);
        
    }
    /**
     * Muestra todos los registros de la tabla Tesis
     */
    private void mostrarTodosAdeudos(){        
        DefaultTableModel temp = cp.allEstudiantesAdeudos();
        actualizarTabla(temp, "¡Lista Vacía!");              
        botonesAcciones(false);        
    }  
    /**
     * Habilita o deshabilita los botones de editar, eliminar y ver
     */
    private void botonesAcciones(boolean state){
        btnVerDetalles.setEnabled(state);        
    }    
    
    /**
     * Controla las busquedas según sea la selección de busqueda
    */
     private void buscar(){
        int select = cmbBuscarPor.getSelectedIndex();
        String busqueda = txtBusqueda.getText();
        DefaultTableModel temp = cp.busquedas(busqueda, select);
        actualizarTabla(temp, "¡No se encontrarón coincidencias!");         
     }
    /**
     * Muestra el resultado en la tabla
     */
    private void actualizarTabla(DefaultTableModel temp, String mensaje){
        if(temp != null && temp.getRowCount() > 0){
                tablaAlumnos.setModel(temp); 
                RenderTabla.centrarDatos(tablaAlumnos);
                scrollTabla.setVisible(true);                
                letreroTabla.setVisible(false);                
                btnVerDetalles.setEnabled(false);                
                btnReporte.setEnabled(true);
            }else{            
                scrollTabla.setVisible(false);
                letreroTabla.setText(mensaje);
                letreroTabla.setVisible(true);
                btnVerDetalles.setEnabled(false);                
                btnReporte.setEnabled(false);
            }        
    } 
    /**
     * Obtiene el registro seleccionado
     */
    private Estudiante obtenerRegistroSeleccionado(){
        int row = tablaAlumnos.getSelectedRow();
        TableModel model = tablaAlumnos.getModel();
        String numero_control = (String)model.getValueAt(row, 0); //fila, columna = 0
        Estudiante estudianteTemp = new Estudiante(numero_control);
        return estudianteTemp;        
    }     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarCarpeta = new javax.swing.JFileChooser();
        panelTitulo = new javax.swing.JPanel();
        letreroConsulta1 = new javax.swing.JLabel();
        panelBarHerramientas = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVerDetalles = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnReporte = new javax.swing.JButton();
        panelBusqueda = new javax.swing.JPanel();
        letreroBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        letreroTabla = new javax.swing.JLabel();

        seleccionarCarpeta.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        seleccionarCarpeta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelTitulo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        panelTitulo.setMinimumSize(new java.awt.Dimension(188, 30));
        panelTitulo.setPreferredSize(new java.awt.Dimension(1103, 30));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        letreroConsulta1.setBackground(Colores.colorPrimary);
        letreroConsulta1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroConsulta1.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta1.setText("Lista de Adeudos");
        letreroConsulta1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta1.setMaximumSize(new java.awt.Dimension(18888, 22));
        letreroConsulta1.setOpaque(true);
        panelTitulo.add(letreroConsulta1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTitulo);

        panelBarHerramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarHerramientas.setMaximumSize(new java.awt.Dimension(11033, 46));
        panelBarHerramientas.setMinimumSize(new java.awt.Dimension(1103, 46));
        panelBarHerramientas.setPreferredSize(new java.awt.Dimension(271, 46));
        panelBarHerramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setToolTipText("Menú");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnHome);
        barraHerramientas.add(jSeparator3);

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        btnVerDetalles.setToolTipText("Muestra los detalles de la tesis seleccionada");
        btnVerDetalles.setEnabled(false);
        btnVerDetalles.setFocusable(false);
        btnVerDetalles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerDetalles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnVerDetalles);

        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pedir-prestado.png"))); // NOI18N
        btnPrestar.setToolTipText("Realizar nuevo prestamo");
        btnPrestar.setFocusable(false);
        btnPrestar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrestar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnPrestar);
        barraHerramientas.add(jSeparator2);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnReporte.setToolTipText("Genera un reporte de todos los prestamos");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnReporte);

        panelBarHerramientas.add(barraHerramientas);

        getContentPane().add(panelBarHerramientas);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusqueda.setMaximumSize(new java.awt.Dimension(11038, 45));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(1103, 45));
        panelBusqueda.setPreferredSize(new java.awt.Dimension(974, 45));
        panelBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        letreroBuscarPor.setText("Buscar por:");
        panelBusqueda.add(letreroBuscarPor);

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Número Control", "Nombre" }));
        cmbBuscarPor.setAutoscrolls(true);
        panelBusqueda.add(cmbBuscarPor);

        txtBusqueda.setMaximumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(250, 26));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(500, 26));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        panelBusqueda.add(txtBusqueda);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnMostrarTodo);

        getContentPane().add(panelBusqueda);

        panelContenido.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        panelContenido.setMinimumSize(new java.awt.Dimension(113, 23));
        panelContenido.setPreferredSize(new java.awt.Dimension(454, 404));
        panelContenido.setLayout(new java.awt.CardLayout());

        scrollTabla.setMaximumSize(new java.awt.Dimension(1103, 200));
        scrollTabla.setMinimumSize(new java.awt.Dimension(1103, 200));
        scrollTabla.setPreferredSize(new java.awt.Dimension(1103, 200));

        tablaAlumnos.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Numero de Control", "Nombre(s)", "Primer Apellido", "Segundo Apellido", "Cantidad Adeudos"
            }
        ));
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaAlumnosMousePressed(evt);
            }
        });
        scrollTabla.setViewportView(tablaAlumnos);

        panelContenido.add(scrollTabla, "card3");

        letreroTabla.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTabla.setText("¡Lista Vacía!");
        panelContenido.add(letreroTabla, "letrero");

        getContentPane().add(panelContenido);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAlumnosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMousePressed
        if(evt.getButton() == 1 && evt.getClickCount() == 1){
            btnVerDetalles.setEnabled(true);
        }else if (evt.getButton() == 1 && evt.getClickCount() > 1) {
            Estudiante temp = obtenerRegistroSeleccionado(); 
            cp.dialogoViewAdeudo(temp, this);           
            mostrarTodosAdeudos();            
        }
    }//GEN-LAST:event_tablaAlumnosMousePressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        Estudiante temp = obtenerRegistroSeleccionado(); //Obtiene el estudiante seleccionado
        cp.dialogoViewAdeudo(temp, this);
        mostrarTodosAdeudos();
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        cp.dialogoAdd(this,tablaAlumnos);
        mostrarTodosAdeudos();
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here: 
       cp.generarReporte(seleccionarCarpeta, this);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        mostrarTodosAdeudos();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnPrestar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel letreroBuscarPor;
    private javax.swing.JLabel letreroConsulta1;
    private javax.swing.JLabel letreroTabla;
    private javax.swing.JPanel panelBarHerramientas;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JFileChooser seleccionarCarpeta;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
