/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Modulos;

import com.mycompany.maestria.Controlador.ControllerTesis;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Vista.Componentes.NavBar;
import com.mycompany.maestria.Vista.Colores.Colores;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author omarsilverio
 */
public class ModuloTesis extends javax.swing.JDialog {   
  
   
    private final ControllerTesis ct = new ControllerTesis();    
    
    public ModuloTesis() { 
       this.setJMenuBar(new NavBar(this));
       initComponents();       
       mostrarTodasTesis();  
       this.setTitle("Tesis");
       RenderTabla.cambiarEstiloEncabezados(tablaTesisMaestria);
    }
     /**
     * Controla las busquedas según sea la selección de busqueda
    */
     private void buscar(){
        int select = cmbBuscarPor.getSelectedIndex();
        String busqueda = txtBusqueda.getText();
        DefaultTableModel temp = ct.busquedas(busqueda, select,0);
        if(temp == null) return;
        mostrarResultadosBusquedas(temp, "¡No se encontrarón coincidencias!"); 
        botonesAcciones(false);
     }
    /**
     * Muestra el resultado de las busqueda
     * 
     */
    private void mostrarResultadosBusquedas(DefaultTableModel temp, String mensaje){
        if(temp.getRowCount() > 0){
                tablaTesisMaestria.setModel(temp);
                RenderTabla.centrarDatos(tablaTesisMaestria);
                tablaScroll.setVisible(true);                
                letreroTabla.setVisible(false);
                btnReporte.setEnabled(true);
            }else{
                tablaScroll.setVisible(false);
                letreroTabla.setText(mensaje);
                letreroTabla.setVisible(true);
                btnReporte.setEnabled(false);
            }        
    } 
   /**
     * Muestra todos los registros de la tabla Tesis
     */
    private void mostrarTodasTesis(){        
        DefaultTableModel temp = ct.allTesis();
        mostrarResultadosBusquedas(temp, "¡Lista Vacía!");              
        botonesAcciones(false);        
    } 
    /**
     * Habilita o deshabilita los botones de editar, eliminar y ver
     */
    private void botonesAcciones(boolean state){
        btnModificar.setEnabled(state);
        btnEliminar.setEnabled(state);
        btnVerDetalles.setEnabled(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarCarpeta = new javax.swing.JFileChooser();
        panelInventario = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        letreroConsulta = new javax.swing.JLabel();
        panelBarHerramientas = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnVerDetalles = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAgregar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnReporte = new javax.swing.JButton();
        panelBusqueda = new javax.swing.JPanel();
        letreroBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();
        tablaScroll = new javax.swing.JScrollPane();
        tablaTesisMaestria = new javax.swing.JTable();
        letreroTabla = new javax.swing.JLabel();

        seleccionarCarpeta.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        seleccionarCarpeta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelInventario.setLayout(new javax.swing.BoxLayout(panelInventario, javax.swing.BoxLayout.Y_AXIS));

        panelTitulo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        panelTitulo.setMinimumSize(new java.awt.Dimension(188, 30));
        panelTitulo.setPreferredSize(new java.awt.Dimension(1103, 30));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        letreroConsulta.setBackground(Colores.colorPrimary);
        letreroConsulta.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setText("Lista de Tesis");
        letreroConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setMaximumSize(new java.awt.Dimension(18888, 22));
        letreroConsulta.setOpaque(true);
        panelTitulo.add(letreroConsulta, java.awt.BorderLayout.CENTER);

        panelInventario.add(panelTitulo);

        panelBarHerramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarHerramientas.setMaximumSize(new java.awt.Dimension(11033, 46));
        panelBarHerramientas.setMinimumSize(new java.awt.Dimension(1103, 46));
        panelBarHerramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setToolTipText("Menú");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnHome);
        barraHerramientas.add(jSeparator3);

        btnVerDetalles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view.png"))); // NOI18N
        btnVerDetalles.setToolTipText("Muestra los detalles de la tesis seleccionada");
        btnVerDetalles.setEnabled(false);
        btnVerDetalles.setFocusable(false);
        btnVerDetalles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerDetalles.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerDetallesActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnVerDetalles);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil.png"))); // NOI18N
        btnModificar.setToolTipText("Modifica la tesis seleccionada");
        btnModificar.setEnabled(false);
        btnModificar.setFocusable(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnModificar);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete.png"))); // NOI18N
        btnEliminar.setToolTipText("Elimina la tesis seleccionada");
        btnEliminar.setEnabled(false);
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnEliminar);
        barraHerramientas.add(jSeparator1);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        btnAgregar.setToolTipText("Agregar Nueva Tesis");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnAgregar);
        barraHerramientas.add(jSeparator2);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnReporte.setToolTipText("Genera un reporte de todas las tesis");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnReporte);

        panelBarHerramientas.add(barraHerramientas);

        panelInventario.add(panelBarHerramientas);

        panelBusqueda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBusqueda.setMaximumSize(new java.awt.Dimension(11038, 45));
        panelBusqueda.setMinimumSize(new java.awt.Dimension(1103, 45));
        panelBusqueda.setPreferredSize(new java.awt.Dimension(974, 45));
        panelBusqueda.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        letreroBuscarPor.setText("Buscar por:");
        panelBusqueda.add(letreroBuscarPor);

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título Tesis", "Año", "Autor", "Número Control" }));
        cmbBuscarPor.setAutoscrolls(true);
        panelBusqueda.add(cmbBuscarPor);

        txtBusqueda.setMaximumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(500, 26));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        panelBusqueda.add(txtBusqueda);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar);

        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnMostrarTodo);

        panelInventario.add(panelBusqueda);

        panelContenido.setLayout(new java.awt.CardLayout());

        tablaTesisMaestria.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        tablaTesisMaestria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idTesis", "Autor", "Titulo", "Tema", "Año", "status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaTesisMaestria.setToolTipText("Tabla tesis maestria");
        tablaTesisMaestria.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tablaTesisMaestria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaTesisMaestriaMousePressed(evt);
            }
        });
        tablaScroll.setViewportView(tablaTesisMaestria);

        panelContenido.add(tablaScroll, "tabla");

        letreroTabla.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTabla.setText("¡Lista Vacía!");
        panelContenido.add(letreroTabla, "letrero");

        panelInventario.add(panelContenido);

        getContentPane().add(panelInventario);
    }// </editor-fold>//GEN-END:initComponents
   
 //*************ACCIONES BOTONES***************************
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaTesisMaestriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTesisMaestriaMousePressed
        if(evt.getButton() == 1 && evt.getClickCount() == 1){
            botonesAcciones(true);
        }else if (evt.getButton() == 1 && evt.getClickCount() > 1) {   
            ControllerTesis.dialogViewTesis(tablaTesisMaestria, this);
        }
    }//GEN-LAST:event_tablaTesisMaestriaMousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ct.dialogAddTesis(this,tablaTesisMaestria);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnVerDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerDetallesActionPerformed
        ControllerTesis.dialogViewTesis(tablaTesisMaestria, this);
    }//GEN-LAST:event_btnVerDetallesActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         ct.dialogEditTesis(tablaTesisMaestria, this);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        mostrarTodasTesis();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        ct.generarReporte(seleccionarCarpeta, this);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        ct.eliminarTesis(this, tablaTesisMaestria);
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnVerDetalles;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel letreroBuscarPor;
    private javax.swing.JLabel letreroConsulta;
    private javax.swing.JLabel letreroTabla;
    private javax.swing.JPanel panelBarHerramientas;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JFileChooser seleccionarCarpeta;
    private javax.swing.JScrollPane tablaScroll;
    private javax.swing.JTable tablaTesisMaestria;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
