/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.maestria.Vista.Modulos;

import com.mycompany.maestria.Controlador.ControllerPrestamo;
import com.mycompany.maestria.Controlador.ControllerTesis;
import com.mycompany.maestria.Modelo.Busquedas.RenderTabla;
import com.mycompany.maestria.Vista.Componentes.NavBar;
import com.mycompany.maestria.Vista.Colores.Colores;

import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author omarsilverio
 */
public class ModuloHistorial extends javax.swing.JDialog {
    private JFreeChart grafica;
    private int cant = 4;
    private final ControllerPrestamo cp = new ControllerPrestamo();
    private final ControllerTesis ct = new ControllerTesis();
    //private ControllerTablasExcel cte = new ControllerTablasExcel();
    /**
     * Creates new form GraficasTesis
     */
    public ModuloHistorial() {     
        this.setJMenuBar(new NavBar(this));
        initComponents();
        this.setModal(true);
        graficar(0);   
        btnReporte.setEnabled(false);
        mostrarTodasTesis(); 
        RenderTabla.cambiarEstiloEncabezados(tablaHistorial);
    } 
    
     /**
     * Controla las busquedas según sea la selección de busqueda
    */
     private void buscar(){
        int select = cmbBuscarPor.getSelectedIndex();
        String busqueda = txtBusqueda.getText();
        DefaultTableModel temp = ct.busquedas(busqueda, select,1);
        if(temp == null) return;
        mostrarResultadosBusquedas(temp, "¡No se encontrarón coincidencias!");         
     }
    
    /**
     * Muestra todos los registros de la tabla Tesis
     */
    private void mostrarTodasTesis(){        
        DefaultTableModel temp = ct.historialTesis();
        mostrarResultadosBusquedas(temp, "¡Lista Vacía!");             
                
    } 
    /**
     * Muestra el resultado de las busqueda
     * 
     */
    private void mostrarResultadosBusquedas(DefaultTableModel temp, String mensaje){
        if(temp.getRowCount() > 0){
                tablaHistorial.setModel(temp);
                RenderTabla.centrarDatos(tablaHistorial);
                tablaScroll.setVisible(true);                
                letreroTabla.setVisible(false);                
            }else{
                tablaScroll.setVisible(false);
                letreroTabla.setText(mensaje);
                letreroTabla.setVisible(true);
                btnReporte.setEnabled(false);
            }        
    } 
   
    private void graficar(int etiqueta){        
        DefaultCategoryDataset datosTemp = cp.getDatosGrafica(etiqueta,cant);         
        if(datosTemp != null && datosTemp.getRowCount() > 0){
            btnReporte.setEnabled(true);            
            letreroDatos.setVisible(false);
             grafica = ChartFactory.createBarChart("Tesis más consultadas",
             "Tesis", "Cant. Prestamos", datosTemp,PlotOrientation.HORIZONTAL, true, true, false);
             ChartPanel panel = new ChartPanel(grafica);             
             areaGrafica.setViewportView(panel);    
             areaGrafica.setVisible(true);
        }else{
            btnReporte.setEnabled(false);
            areaGrafica.setVisible(false);
            letreroDatos.setVisible(true);
        }
    }
    
    private void activarPanelGrafica(boolean estado){
        panelGrafica.setVisible(estado);   
        btnReporte.setEnabled(!estado);
        barraGrafica.setVisible(estado);
    }
    private void activarPanelHistorial(boolean estado){
        panelHistorial.setVisible(estado);
        barraHistorial.setVisible(estado);
    }    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarCarpeta = new javax.swing.JFileChooser();
        panelTitulo = new javax.swing.JPanel();
        letreroConsulta = new javax.swing.JLabel();
        barraHeramientas = new javax.swing.JPanel();
        barraHerramientas = new javax.swing.JToolBar();
        btnHome = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnReporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        panelBarHerramientas = new javax.swing.JPanel();
        barraGrafica = new javax.swing.JPanel();
        letreroEtiqueta = new javax.swing.JLabel();
        cmbEtiqueta = new javax.swing.JComboBox<>();
        letreroNumDatos = new javax.swing.JLabel();
        spinNumDatos = new javax.swing.JSpinner();
        barraHistorial = new javax.swing.JPanel();
        letreroBuscarPor = new javax.swing.JLabel();
        cmbBuscarPor = new javax.swing.JComboBox<>();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        panelTabContenido = new javax.swing.JTabbedPane();
        panelGrafica = new javax.swing.JPanel();
        areaGrafica = new javax.swing.JScrollPane();
        letreroDatos = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JPanel();
        tablaScroll = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        letreroTabla = new javax.swing.JLabel();

        seleccionarCarpeta.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        seleccionarCarpeta.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        panelTitulo.setMaximumSize(new java.awt.Dimension(2147483647, 30));
        panelTitulo.setMinimumSize(new java.awt.Dimension(188, 30));
        panelTitulo.setPreferredSize(new java.awt.Dimension(1103, 30));
        panelTitulo.setLayout(new java.awt.BorderLayout());

        letreroConsulta.setBackground(Colores.colorPrimary);
        letreroConsulta.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroConsulta.setForeground(new java.awt.Color(255, 255, 255));
        letreroConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setText("Historial Prestamos");
        letreroConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        letreroConsulta.setMaximumSize(new java.awt.Dimension(18888, 22));
        letreroConsulta.setOpaque(true);
        panelTitulo.add(letreroConsulta, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelTitulo);

        barraHeramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barraHeramientas.setMaximumSize(new java.awt.Dimension(11033, 46));
        barraHeramientas.setMinimumSize(new java.awt.Dimension(1103, 46));
        barraHeramientas.setPreferredSize(new java.awt.Dimension(271, 46));
        barraHeramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnHome.setToolTipText("Menú");
        btnHome.setFocusable(false);
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnHome);
        barraHerramientas.add(jSeparator3);

        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/file.png"))); // NOI18N
        btnReporte.setToolTipText("Genera un reporte de todos los adeudos");
        btnReporte.setFocusable(false);
        btnReporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReporte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        barraHerramientas.add(btnReporte);
        barraHerramientas.add(jSeparator1);

        barraHeramientas.add(barraHerramientas);

        getContentPane().add(barraHeramientas);

        panelBarHerramientas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarHerramientas.setMaximumSize(new java.awt.Dimension(11038, 45));
        panelBarHerramientas.setMinimumSize(new java.awt.Dimension(1103, 45));
        panelBarHerramientas.setPreferredSize(new java.awt.Dimension(974, 45));
        panelBarHerramientas.setLayout(new java.awt.CardLayout());

        barraGrafica.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        letreroEtiqueta.setText("Etiqueta:");
        barraGrafica.add(letreroEtiqueta);

        cmbEtiqueta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "idTesis", "Autor", "Titulo" }));
        cmbEtiqueta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEtiquetaItemStateChanged(evt);
            }
        });
        barraGrafica.add(cmbEtiqueta);

        letreroNumDatos.setText("Número de Datos:");
        barraGrafica.add(letreroNumDatos);

        spinNumDatos.setModel(new javax.swing.SpinnerNumberModel(5, 1, 10, 1));
        spinNumDatos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinNumDatosStateChanged(evt);
            }
        });
        barraGrafica.add(spinNumDatos);

        panelBarHerramientas.add(barraGrafica, "card2");

        barraHistorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        barraHistorial.setMaximumSize(new java.awt.Dimension(11038, 45));
        barraHistorial.setMinimumSize(new java.awt.Dimension(1103, 45));
        barraHistorial.setPreferredSize(new java.awt.Dimension(974, 45));
        barraHistorial.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        letreroBuscarPor.setText("Buscar por:");
        barraHistorial.add(letreroBuscarPor);

        cmbBuscarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Título Tesis", "Año", "Autor", "Número Control" }));
        cmbBuscarPor.setAutoscrolls(true);
        barraHistorial.add(cmbBuscarPor);

        txtBusqueda.setMaximumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setMinimumSize(new java.awt.Dimension(500, 26));
        txtBusqueda.setPreferredSize(new java.awt.Dimension(500, 26));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        barraHistorial.add(txtBusqueda);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        barraHistorial.add(btnBuscar);

        btnMostrarTodo.setText("Mostrar Todo");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        barraHistorial.add(btnMostrarTodo);

        panelBarHerramientas.add(barraHistorial, "card3");

        getContentPane().add(panelBarHerramientas);

        panelTabContenido.setMinimumSize(new java.awt.Dimension(113, 23));
        panelTabContenido.setPreferredSize(new java.awt.Dimension(454, 404));
        panelTabContenido.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                panelTabContenidoStateChanged(evt);
            }
        });

        panelGrafica.setLayout(new java.awt.CardLayout());
        panelGrafica.add(areaGrafica, "card2");

        letreroDatos.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroDatos.setText("¡No Hay Datos!");
        panelGrafica.add(letreroDatos, "letrero");

        panelTabContenido.addTab("Grafica", panelGrafica);

        panelHistorial.setLayout(new java.awt.CardLayout());

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "IdTesis", "Titulo", "Autor", "Año", "Nº Solicitudes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaHistorialMousePressed(evt);
            }
        });
        tablaScroll.setViewportView(tablaHistorial);

        panelHistorial.add(tablaScroll, "card2");

        letreroTabla.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        letreroTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        letreroTabla.setText("¡No Hay Datos!");
        panelHistorial.add(letreroTabla, "letrero");

        panelTabContenido.addTab("Historial", panelHistorial);

        getContentPane().add(panelTabContenido);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:      
        cp.generarReporteTesisAdeudos(seleccionarCarpeta, this);
    }//GEN-LAST:event_btnReporteActionPerformed

    private void cmbEtiquetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEtiquetaItemStateChanged
        // TODO add your handling code here:
        int seleccion = cmbEtiqueta.getSelectedIndex();           
        graficar(seleccion);
        this.validate();
    }//GEN-LAST:event_cmbEtiquetaItemStateChanged
    
    private void spinNumDatosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinNumDatosStateChanged
        // TODO add your handling code here:
        cant = Integer.parseInt(spinNumDatos.getValue().toString());
        int seleccion = cmbEtiqueta.getSelectedIndex();           
        graficar(seleccion);
    }//GEN-LAST:event_spinNumDatosStateChanged

    private void panelTabContenidoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_panelTabContenidoStateChanged
        // TODO add your handling code here:
        int select = panelTabContenido.getSelectedIndex();
        switch(select){
            case 0 -> {
                activarPanelHistorial(false);
                activarPanelGrafica(true);                
            }
            case 1 -> {
                activarPanelHistorial(true);
                activarPanelGrafica(false);  
            }
            default -> {
                    activarPanelHistorial(false);
                    activarPanelGrafica(true);  
                    }
        }
    }//GEN-LAST:event_panelTabContenidoStateChanged

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        mostrarTodasTesis();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        buscar();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void tablaHistorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHistorialMousePressed
        // TODO add your handling code here:
        if(evt.getButton() == 1 && evt.getClickCount() == 1){                
                
            }else if (evt.getButton() == 1 && evt.getClickCount() > 1) {                
               ControllerPrestamo.dialogViewPrestamo(tablaHistorial, this);
            }
    }//GEN-LAST:event_tablaHistorialMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane areaGrafica;
    private javax.swing.JPanel barraGrafica;
    private javax.swing.JPanel barraHeramientas;
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JPanel barraHistorial;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> cmbBuscarPor;
    private javax.swing.JComboBox<String> cmbEtiqueta;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JLabel letreroBuscarPor;
    private javax.swing.JLabel letreroConsulta;
    private javax.swing.JLabel letreroDatos;
    private javax.swing.JLabel letreroEtiqueta;
    private javax.swing.JLabel letreroNumDatos;
    private javax.swing.JLabel letreroTabla;
    private javax.swing.JPanel panelBarHerramientas;
    private javax.swing.JPanel panelGrafica;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JTabbedPane panelTabContenido;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JFileChooser seleccionarCarpeta;
    private javax.swing.JSpinner spinNumDatos;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JScrollPane tablaScroll;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
